//! Controller for `docs.html`: chart switching, pan and zoom, and showing the
//! code behind a box.
//!
//! The diagrams are static SVG generated by `ccm-docgen`, so this only has to
//! move a transform around and copy text into a pane. Without it the page is
//! still readable — the charts are plain SVG and the code is in the document.

use crate::{element, restore_theme, set_text};
use std::cell::RefCell;
use std::rc::Rc;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{Document, Element, HtmlElement, MouseEvent, WheelEvent};

/// Zoom range. Below the floor the labels stop being readable; above the
/// ceiling there is nothing left to see.
const MIN_SCALE: f64 = 0.35;
const MAX_SCALE: f64 = 3.0;

#[derive(Clone, Copy)]
struct View {
    scale: f64,
    x: f64,
    y: f64,
}

impl Default for View {
    fn default() -> Self {
        Self {
            scale: 1.0,
            x: 0.0,
            y: 0.0,
        }
    }
}

struct DocsState {
    document: Document,
    chart: String,
    view: View,
    dragging: Option<(f64, f64)>,
}

impl DocsState {
    /// The `<div class="chart-stage">` holding the visible chart's SVG.
    fn stage(&self) -> Option<Element> {
        self.document
            .query_selector(&format!("#panel-{} .chart-stage", self.chart))
            .ok()
            .flatten()
    }
}

fn apply_view(state: &Rc<RefCell<DocsState>>) {
    let app = state.borrow();
    let Some(stage) = app.stage() else {
        return;
    };
    let view = app.view;
    let _ = stage.set_attribute(
        "style",
        &format!(
            "transform: translate({:.1}px, {:.1}px) scale({:.3})",
            view.x, view.y, view.scale
        ),
    );
    set_text(
        &app.document,
        "zoomLevel",
        &format!("{:.0}%", view.scale * 100.0),
    );
}

fn zoom_by(state: &Rc<RefCell<DocsState>>, factor: f64) {
    {
        let mut app = state.borrow_mut();
        app.view.scale = (app.view.scale * factor).clamp(MIN_SCALE, MAX_SCALE);
    }
    apply_view(state);
}

fn fit(state: &Rc<RefCell<DocsState>>) {
    {
        let mut app = state.borrow_mut();
        app.view = View::default();
    }
    apply_view(state);
}

fn show_chart(state: &Rc<RefCell<DocsState>>, id: &str) {
    {
        let mut app = state.borrow_mut();
        app.chart = id.to_owned();
        app.view = View::default();
        let document = app.document.clone();
        drop(app);
        if let Ok(panels) = document.query_selector_all(".chart-panel") {
            for index in 0..panels.length() {
                if let Some(panel) = panels
                    .item(index)
                    .and_then(|n| n.dyn_into::<Element>().ok())
                {
                    let matches = panel.id() == format!("panel-{id}");
                    let _ = panel.class_list().toggle_with_force("hidden", !matches);
                }
            }
        }
        if let Ok(tabs) = document.query_selector_all(".chart-tab") {
            for index in 0..tabs.length() {
                if let Some(tab) = tabs.item(index).and_then(|n| n.dyn_into::<Element>().ok()) {
                    let matches = tab.get_attribute("data-chart").as_deref() == Some(id);
                    let _ = tab.class_list().toggle_with_force("active", matches);
                }
            }
        }
    }
    apply_view(state);
}

/// Copies the source of `name` into the code pane.
fn show_code(state: &Rc<RefCell<DocsState>>, name: &str) {
    let app = state.borrow();
    let document = &app.document;
    let Ok(Some(template)) = document.query_selector(&format!("template[data-code=\"{name}\"]"))
    else {
        return;
    };
    // A <template>'s children live in its content fragment, not under the
    // element, so text_content() on the element itself comes back empty.
    let code = template
        .dyn_ref::<web_sys::HtmlTemplateElement>()
        .and_then(|template| template.content().text_content())
        .unwrap_or_default();
    let source = template
        .get_attribute("data-source")
        .unwrap_or_else(|| "the crate".into());
    set_text(document, "codeTitle", name);
    set_text(document, "codeSource", &source);
    element::<Element>(document, "codeBody").set_text_content(Some(&code));
    let _ = element::<Element>(document, "codePane")
        .class_list()
        .add_1("open");

    // Mark the box so it is obvious which one is being read.
    if let Ok(previous) = document.query_selector_all(".node.selected") {
        for index in 0..previous.length() {
            if let Some(node) = previous
                .item(index)
                .and_then(|n| n.dyn_into::<Element>().ok())
            {
                let _ = node.class_list().remove_1("selected");
            }
        }
    }
    if let Ok(Some(current)) =
        document.query_selector(&format!("#panel-{} [data-fn=\"{name}\"]", app.chart))
    {
        let _ = current.class_list().add_1("selected");
    }
}

/// Walks up from an event target to the nearest box that carries code.
fn function_at(target: &JsValue) -> Option<String> {
    let mut node = target.clone().dyn_into::<Element>().ok()?;
    for _ in 0..6 {
        if let Some(name) = node.get_attribute("data-fn") {
            return Some(name);
        }
        node = node.parent_element()?;
    }
    None
}

/// Entry point for `docs.html`.
///
/// # Errors
///
/// Returns an error when the window or document is unavailable.
#[wasm_bindgen]
pub fn start_docs() -> Result<(), JsValue> {
    let window = web_sys::window().ok_or_else(|| JsValue::from_str("window unavailable"))?;
    let document = window
        .document()
        .ok_or_else(|| JsValue::from_str("document unavailable"))?;
    restore_theme(&document);

    let first = document
        .query_selector(".chart-tab")
        .ok()
        .flatten()
        .and_then(|tab| tab.get_attribute("data-chart"))
        .unwrap_or_else(|| "drop".into());

    let state = Rc::new(RefCell::new(DocsState {
        document: document.clone(),
        chart: first.clone(),
        view: View::default(),
        dragging: None,
    }));

    crate::hook_theme_toggle(&document, || {});

    // Chart tabs.
    if let Ok(tabs) = document.query_selector_all(".chart-tab") {
        for index in 0..tabs.length() {
            let Some(tab) = tabs
                .item(index)
                .and_then(|n| n.dyn_into::<HtmlElement>().ok())
            else {
                continue;
            };
            let id = tab.get_attribute("data-chart").unwrap_or_default();
            let state = Rc::clone(&state);
            let closure = Closure::<dyn FnMut()>::new(move || show_chart(&state, &id));
            let _ = tab.add_event_listener_with_callback("click", closure.as_ref().unchecked_ref());
            closure.forget();
        }
    }

    // Zoom controls.
    for (id, factor) in [("zoomIn", 1.25_f64), ("zoomOut", 0.8)] {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut()>::new(move || zoom_by(&state, factor));
        let _ = element::<HtmlElement>(&document, id)
            .add_event_listener_with_callback("click", closure.as_ref().unchecked_ref());
        closure.forget();
    }
    {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut()>::new(move || fit(&state));
        let _ = element::<HtmlElement>(&document, "zoomFit")
            .add_event_listener_with_callback("click", closure.as_ref().unchecked_ref());
        closure.forget();
    }
    {
        let owned = document.clone();
        let closure = Closure::<dyn FnMut()>::new(move || {
            let _ = element::<Element>(&owned, "codePane")
                .class_list()
                .remove_1("open");
        });
        let _ = element::<HtmlElement>(&document, "codeClose")
            .add_event_listener_with_callback("click", closure.as_ref().unchecked_ref());
        closure.forget();
    }

    let charts: HtmlElement = element(&document, "charts");

    // Click a box to read its function.
    {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut(MouseEvent)>::new(move |event: MouseEvent| {
            if let Some(name) = event.target().and_then(|t| function_at(&t)) {
                show_code(&state, &name);
            }
        });
        let _ = charts.add_event_listener_with_callback("click", closure.as_ref().unchecked_ref());
        closure.forget();
    }

    // Wheel to zoom.
    {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut(WheelEvent)>::new(move |event: WheelEvent| {
            event.prevent_default();
            let factor = if event.delta_y() < 0.0 { 1.12 } else { 0.89 };
            zoom_by(&state, factor);
        });
        // Not passive: the handler calls preventDefault so the page does not
        // scroll while the reader is zooming the diagram.
        let options = web_sys::AddEventListenerOptions::new();
        options.set_passive(false);
        let _ = charts.add_event_listener_with_callback_and_add_event_listener_options(
            "wheel",
            closure.as_ref().unchecked_ref(),
            &options,
        );
        closure.forget();
    }

    // Drag to pan.
    {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut(MouseEvent)>::new(move |event: MouseEvent| {
            let mut app = state.borrow_mut();
            app.dragging = Some((
                f64::from(event.client_x()) - app.view.x,
                f64::from(event.client_y()) - app.view.y,
            ));
        });
        let _ =
            charts.add_event_listener_with_callback("mousedown", closure.as_ref().unchecked_ref());
        closure.forget();
    }
    {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut(MouseEvent)>::new(move |event: MouseEvent| {
            let moved = {
                let mut app = state.borrow_mut();
                match app.dragging {
                    Some((ox, oy)) => {
                        app.view.x = f64::from(event.client_x()) - ox;
                        app.view.y = f64::from(event.client_y()) - oy;
                        true
                    }
                    None => false,
                }
            };
            if moved {
                apply_view(&state);
            }
        });
        let _ =
            charts.add_event_listener_with_callback("mousemove", closure.as_ref().unchecked_ref());
        closure.forget();
    }
    for event in ["mouseup", "mouseleave"] {
        let state = Rc::clone(&state);
        let closure = Closure::<dyn FnMut()>::new(move || {
            state.borrow_mut().dragging = None;
        });
        let _ = charts.add_event_listener_with_callback(event, closure.as_ref().unchecked_ref());
        closure.forget();
    }

    show_chart(&state, &first);
    Ok(())
}
