#!/usr/bin/env bash
# Generates docs/algorithm-flowcharts.md.
#
# The prose and the diagrams live here; the code blocks are lifted straight out
# of the crates, so a function shown in the document is the function that runs.
# Re-run after changing any of the functions it quotes:
#
#   ./scripts/gen-flowcharts.sh
#
# CI checks the result is current, the same way it checks the WASM package.
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_dir"

out="docs/algorithm-flowcharts.md"

# Prints one function, with the doc comment above it.
#
# rustfmt puts a function's closing brace at the same indentation as its `fn`,
# which is what makes this exact rather than a brace-counting guess that string
# literals would defeat.
emit() {
  local file="$1" name="$2"
  awk -v name="$name" '
    # Collect doc comments so the reason a function exists travels with it.
    /^[[:space:]]*\/\/\// { doc[nd++] = $0; next }
    /^[[:space:]]*#\[/    { doc[nd++] = $0; next }
    {
      if (!inside) {
        line = $0
        sub(/^[[:space:]]*/, "", line)
        if (line ~ ("^(pub )?(async )?fn " name "([<(]|$)")) {
          inside = 1
          match($0, /^[[:space:]]*/)
          indent = substr($0, 1, RLENGTH)
          closing = indent "}"
          for (i = 0; i < nd; i++) print doc[i]
          print $0
          next
        }
        nd = 0
        next
      }
      print $0
      if ($0 == closing) exit
    }
  ' "$file"
}

# Emits a fenced Rust block for each named function.
block() {
  local file="$1"; shift
  for name in "$@"; do
    printf '```rust\n' >> "$out"
    emit "$file" "$name" >> "$out"
    printf '```\n\n' >> "$out"
  done
}

DROP=crates/ccm-algorithms/src/lib.rs
HELP=crates/ccm-help-scouts/src/lib.rs
P1=crates/ccm-p1tree/src/lib.rs

cat > "$out" <<'HEADER'
# Algorithm flowcharts

One flowchart per algorithm, with the code of every function the chart names.

The charts are the control flow as implemented, not as idealised: where the
implementation departs from a paper, the chart shows what the code does and the
note beside it says why. Read [behavior-spec.md](behavior-spec.md) for
Drop-and-Freeze and Help-by-Scouts, and [p1tree.md](p1tree.md) for P1Tree,
before drawing conclusions from any of them.

> Generated by [`scripts/gen-flowcharts.sh`](../scripts/gen-flowcharts.sh). The
> code blocks are extracted from the crates, so editing this file by hand will
> be overwritten. Re-run the script after changing any function it quotes.

## Contents

- [Drop and Freeze](#drop-and-freeze) — `ccm-algorithms`
- [Help by Scouts](#help-by-scouts) — `ccm-help-scouts`
- [P1Tree](#p1tree) — `ccm-p1tree`

---

## Drop and Freeze

Three phases per round, over the agents standing on each node. Unsettled agents
fan out one per port to look at a neighbour, come back carrying one bit — was it
occupied — and then one of them settles while the rest move on together through
a port a probe reported empty. When no empty port is left the group backtracks
along the port it first arrived by, so the walk is a DFS whose tree is held by
the settled agents.

```mermaid
flowchart TD
    A["simulate_with()"] --> B["canonicalize_ports()"]
    B --> C{"all_settled()?"}
    C -- yes --> Z["Termination::Completed"]
    C -- no --> D{"round &lt; round_limit?"}
    D -- no --> Y["Termination::RoundLimitReached"]
    D -- yes --> E["probe_out()"]
    E --> F["probe_back()"]
    F --> G["move_out()"]
    G --> H["validate_state()"]
    H --> C

    E -. "ports in DFS-cursor order" .-> E1["ordered_ports()"]
    G -. "one settles, rest move as a group" .-> G1["scouts_for_count()"]
```

`canonicalize_ports` is a compatibility decision rather than an algorithmic one:
the Python reference replaced any supplied local port labels with canonical
sorted-neighbour ones, so this port does too. It means Drop-and-Freeze ignores
the port assignment the experiment asked for.

HEADER

block "$DROP" simulate_with canonicalize_ports ordered_ports probe_out probe_back move_out

cat >> "$out" <<'HEADER'
---

## Help by Scouts

Also a DFS, but settled agents help. A settled agent whose node can spare it
vacates and travels with the unsettled group as a scout, so several ports can be
probed in the same round instead of one at a time. Scouts later retrace the tree
in post-order and drop back onto the nodes they own, so the run still ends one
agent per node.

```mermaid
flowchart TD
    A["run() / simulate()"] --> B["run_transitions()"]
    B --> C{"unsettled agents left?"}
    C -- no --> R["retrace()"]
    C -- yes --> D["settle() highest ID at head"]
    D --> E["can_vacate()"]
    E -- "settledScout" --> F["joins the scout pool"]
    E -- "settled" --> G
    F --> G["parallel_probe()"]
    G --> H["candidate_rank() picks the next port"]
    H -- "port found" --> I["move_group() forward"]
    H -- "none" --> J["move_group() to parentPort"]
    I --> K["update_node_type()"]
    J --> K
    K --> C
    R --> S["settle_vacated_at() each home"]
    S --> T["validate_final()"]

    G -. "edge classification" .-> G1["edge_type()"]
```

HEADER

block "$HELP" run_transitions parallel_probe candidate_rank can_vacate move_group retrace

cat >> "$out" <<'HEADER'
---

## P1Tree

`DFS_P1Tree` from Pattanayak, Kshemkalyani, Kumar, Molla and Sharma, *Optimal
Dispersion Under Asynchrony*. A DFS that builds a **port-one tree**: every
vertex ends up with an incident tree edge carrying port 1 at one of its ends.
Edges are preferred `tp1 > t11 ~ t1q > tpq`, and a node reached only through a
`tpq` edge is parked as `partiallyVisited` until its port-1 neighbour comes to
claim it.

Two details carry the `O(k)` bound, and losing either makes the cost scale with
the graph instead of with the agents:

- `neighbourhood_search` **stops at the first batch that finds somewhere to go**.
  Remark 1 bounds the search by the agent count, not the degree, because at most
  `k` nodes are ever occupied, so while any agent is unsettled some probed
  neighbour must be empty.
- `traverse` **stops at dispersion**. Section 5: "the process continues until no
  unsettled agents remain". The tree at that moment need not yet be a P1Tree —
  a parked node may still hold a `tpq` parent edge — and that is fine, because
  dispersion is the goal.

```mermaid
flowchart TD
    A["run() / simulate()"] --> B["settle_highest_at(root)"]
    B --> C["traverse()"]
    C --> D{"dispersed_at_step set?"}
    D -- yes --> R["retrace()"]
    D -- no --> E["neighbourhood_search()"]

    subgraph probe ["parallel probe, one batch at a time"]
        E --> E1["probe_party() assigns ports to scouts"]
        E1 --> E2["scouts step out together"]
        E2 --> E3["state_of() / probe_detour()"]
        E3 --> E4{"choose_next_edge() found one?"}
        E4 -- no, ports left --> E1
    end

    E4 -- yes --> F{"must_defer()?"}
    E4 -- "no, ports exhausted" --> G{"awaits_port_one()?"}

    F -- yes --> P["mark partiallyVisited"]
    F -- no --> H["advance()"]
    G -- yes --> P
    G -- no --> Q["mark fullyVisited"]

    H --> I["settle_highest_at() if unvisited"]
    I --> J["set_parent() / reconfigure"]
    J --> K["apply_can_vacate() / apply_parent_vacate()"]
    K --> D

    P --> L["apply_can_vacate()"]
    Q --> L
    L --> M["backtrack()"]
    M -- "root popped" --> Z["Termination::Completed"]
    M -- else --> D

    R --> S["post_order() walk, drop each scout at its home"]
```

HEADER

block "$P1" traverse neighbourhood_search choose_next_edge must_defer awaits_port_one advance apply_can_vacate apply_parent_vacate retrace

cat >> "$out" <<'HEADER'
---

## Reading the three together

All three settle one agent per node and all three are depth-first, but they
differ in who does the looking and what the tree is for.

| | Drop and Freeze | Help by Scouts | P1Tree |
| --- | --- | --- | --- |
| Who probes | unsettled agents, one per port | unsettled agents plus vacated settlers | unsettled agents plus vacated settlers |
| Probe cost | one port per agent per round | parallel across scouts | parallel, and stops at the first find |
| Port labels | overwritten by `canonicalize_ports` | as given | as given, and central to the result |
| Tree | incidental to the walk | carries the retrace | the object being built |
| Stops when | every agent is settled | every agent is settled | every agent is settled |

The port-label row is the one that catches people out. Drop-and-Freeze discards
the port assignment an experiment asked for, so sweeping `--ports` changes
nothing for it; P1Tree's whole behaviour turns on which edges happen to carry
port 1.
HEADER

echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"
